### ISSUE TITLE
[1.19.2][Bug]Cherry Trees not rendering on the maps/JourneyMap

### ISSUE THREAD

**Issue by TheXev** [skniro/Maple#14]
This didn't use to be an issue, but after updating to 1.0.0 Beta2, the mini map no longer seems to render the cherry trees both on vanilla maps and on Journey Map.  They rendered fine in Beta1 and in the Alpha builds for 1.0.0.

**Comment by skniro** [comment]
The reason is a wrong mapcolor settings.I will fix it quickly.Thanks your report.

**Comment by TheXev** [comment]
This report needs to be reopened.  The bug exist again in 1.1.0 Beta 1.
