### ISSUE TITLE
Cherry tree decomposition

### ISSUE THREAD

**Issue by Snowspells** [skniro/Maple#2]
When cherry trees begin leaf decomposition, they only drop cherry leaf blocks, not sticks or saplings.

**Comment by skniro** [comment]
Thanks your report.This bug will be fix in next version.The reason is my data generator have some problem.

**Comment by skniro** [comment]
https://github.com/skniro/Maple/commit/93923659bf1683b595c5beea11836b18cd8734d3

**Comment by skniro** [comment]
Fix of https://github.com/skniro/Maple/commit/93923659bf1683b595c5beea11836b18cd8734d3
