### ISSUE TITLE
maple and cherry saplings drop flower pots and not saplings

### ISSUE THREAD

**Issue by h3oCharles** [skniro/Maple#25]
![2024-08-25_22 28 01](https://github.com/user-attachments/assets/7a6461ed-232f-4bc8-89a9-f627bbb450ea)

maple-1.19.4-1.0.0-Beta1-Fabric

stuck on this version cuz I'm in a modded SMP

**Comment by skniro** [comment]
Fix in 1.19.4-1.0.1.

**Comment by h3oCharles** [comment]
had a look at the update, and it's not fixed. i didn't mean saplings in a flower pot, I meant saplings placed on their own.
in fact, I made a datapack that changed the loot tables of the saplings

[goofy ahh saplings.zip](https://github.com/user-attachments/files/16768505/goofy.ahh.saplings.zip)

**Comment by skniro** [comment]
Fix in 1.19.4-1.0.2. Sorry i understand it to other bug.
