### ISSUE TITLE
incompatability with rechiseled?

### ISSUE THREAD

**Issue by h3oCharles** [skniro/Maple#26]
idk how to phrase this exactly, but when Maple[?] disables bamboo and cherry planks and add their own, they can't be used with Rechiseled's chisel to make block variants

maple-1.19.4-1.0.0-Beta1-Fabric.jar
rechiseled-1.1.6-fabric-mc1.19.4.jar

here's the rest of the mods, just in case. all configs are default
![image](https://github.com/user-attachments/assets/17268cde-e236-4482-9a23-cf39a54a2414)

![2024-08-25_22 30 55](https://github.com/user-attachments/assets/02634c10-ca12-48ec-aceb-5eef2704217d)
![2024-08-25_22 31 01](https://github.com/user-attachments/assets/b7212857-7a0e-40f5-a717-35b422958727)

**Comment by skniro** [comment]
Incompatability with Rechiseled. Because maple and minecraft have different id. Rechiseled port for minecraft's cherry and bamboo planks or not maple's.

**Comment by skniro** [comment]
If I want port it need speed lot time to write a compatibilitie part.

**Comment by h3oCharles** [comment]
can one add recipes for (or using) disabled items? how about a temporary solution of adding some conversion to go from one plank type to another?

**Comment by skniro** [comment]
I test it can work, but based my mod [life cycle](https://[lifecycle.sttsakara.top](https://lifecycle.sttsakara.top/)/) 1.19.4 version is EOL version.

**Comment by skniro** [comment]
But this time i still decide add it, because i like use chisel's block to build my house.

**Comment by skniro** [comment]
![image](https://github.com/user-attachments/assets/10c712cd-5651-429e-b476-779f0acfe9e2)

**Comment by skniro** [comment]
![image](https://github.com/user-attachments/assets/63d63bd6-b258-4d27-926f-74995dc986d3)

**Comment by skniro** [comment]
Try 1.0.3

**Comment by h3oCharles** [comment]
OMG IT WORKS
