### ISSUE TITLE
1.20.1安装Maple后与“YUNG的xx”系列模组发生冲突

### ISSUE THREAD

**Issue by MCER2020** [skniro/Maple#29]
游戏版本：1.20.1
Forge版本：47.3.0
Maple版本：1.3.5
YUNG's Better Strongholds 版本：4.0.3
Repurposed Structures 版本：7.1.15

描述：
在同时安装“结构变体”与“YUNG 的xx”系列模组时无异常，所有的结构正常生成，但是在安装了Maple之后，部分“结构变体”与“YUNG 的xx”模组无法生成对应的结构，如“YUNG 的要塞优化”模组，无法在主世界生成要塞，导致生存模式下无法找到要塞并进入末地，经测试，除了要塞外，还有另外几个“YUNG”系列的模组也无法生成对应的结构。
截图：
![problem](https://github.com/user-attachments/assets/ebeb5ff1-292a-4b08-b373-a544c19a9c29)

相关链接：
YUNG's Better Strongholds：https://github.com/YUNG-GANG/YUNGs-Better-Strongholds
Repurposed Structures：https://github.com/TelepathicGrunt/RepurposedStructures

**Comment by skniro** [comment]
May cause this issue's mod is Terrablender

**Comment by skniro** [comment]
Remove maple but add terrablender test again。

**Comment by skniro** [comment]
I test it shoud cause by maple's tag. Will fix in next version.

**Comment by skniro** [comment]
Try 1.3.7
