### ISSUE TITLE
Cherry Blossom Sign is not pink but red 

### ISSUE THREAD

**Issue by Kekschankeks** [skniro/Maple#3]
https://cdn.discordapp.com/attachments/1091454276464803954/1122878079136706560/image.png

With and without Texture Pack it looks like this

**Comment by skniro** [comment]
Thanks your report.But I can't reappear this issue in my locate.It is image.
![屏幕截图 2023-06-27 223909](https://github.com/skniro/Maple/assets/46392259/3a5970f8-b6fb-4fb9-8a10-4e674d0539e5)

**Comment by skniro** [comment]
Could you provide error report log? It can help me to fix this issue.
