### ISSUE TITLE
Bamboo Mosaic and Bamboo Mosaic Slab are named the same

### ISSUE THREAD

**Issue by Czompi** [skniro/Maple#7]
Thank you for the quick fix for my PR/issue. I noticed an another one. The values of `block.maple.bamboo_mosaic` and `block.maple.bamboo_mosaic_slab` are the same.

**Comment by skniro** [comment]
Thanks your report.
Fix in https://github.com/skniro/Maple/commit/b1723fc15df608ac3f47e5d52f10e019c1bccd0e .
It will release in next version with new item,so it may need a few days.
