### ISSUE TITLE
Bamboo Wood Recipe bugged

### ISSUE THREAD

**Issue by GlitchedChaser** [skniro/Maple#9]
for some reason when i look at recipe for bamboo wood
the recipe input is blank

and bamboo block does not craft into bamboo

**Comment by skniro** [comment]
![屏幕截图 2023-07-12 122427](https://github.com/skniro/Maple/assets/46392259/39ab9d01-d50b-4561-a1b7-4fe0c1446529)

**Comment by skniro** [comment]
Bamboo block does can craft into bamboo in my clients. Could you upload some another file to help me fix it.

**Comment by skniro** [comment]
Bamboo plank recipe is wrong. I will fix it.

**Comment by skniro** [comment]
Fix in https://github.com/skniro/Maple/commit/79d72211df15426a53e171f350a138f93abdc763
